# Generated by Django 6.0.5 on 2026-05-12 16:07

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='Россия', max_length=100, verbose_name='Страна')),
                ('region', models.CharField(max_length=100, verbose_name='Регион (Край/Область)')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='Район')),
                ('city', models.CharField(max_length=100, verbose_name='Город/Село')),
                ('street', models.CharField(max_length=150, verbose_name='Улица')),
                ('building_number', models.CharField(max_length=10, verbose_name='Номер дома/строения')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Почтовый индекс')),
                ('description', models.TextField(blank=True, verbose_name='Примечание к адресу')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название должности')),
                ('description', models.TextField(blank=True, verbose_name='Описание должности')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название предмета')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='custom_user_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название школы')),
                ('description', models.TextField(blank=True, verbose_name='Описание школы')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='school_photos/', verbose_name='Логотип или фото школы')),
                ('addresses', models.ManyToManyField(blank=True, to='school.address', verbose_name='Адреса школы')),
            ],
            options={
                'verbose_name': 'Школа',
                'verbose_name_plural': 'Школы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('hire_year', models.IntegerField(verbose_name='Год приема на работу')),
                ('description', models.TextField(blank=True, verbose_name='О сотруднике')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee_photos/', verbose_name='Фотография сотрудника')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.position', verbose_name='Занимаемая должность')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school', verbose_name='Место работы')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900)], verbose_name='Год начала обучения')),
                ('end_year', models.IntegerField(editable=False, verbose_name='Год окончания обучения')),
                ('grade_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Номер класса')),
                ('letter', models.CharField(blank=True, max_length=1, null=True, verbose_name='Буква класса')),
                ('description', models.TextField(blank=True, verbose_name='Описание класса')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='class_photos/', verbose_name='Фото класса')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school', verbose_name='Учебное заведение')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
                'ordering': ['start_year', 'grade_number', 'letter'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('description', models.TextField(blank=True, verbose_name='О себе или примечания')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photos/', verbose_name='Фотография ученика')),
                ('user', models.OneToOneField(blank=True, help_text='Учетная запись, которой принадлежит этот ученик.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.customuser', verbose_name='Связанный пользователь')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentClassHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='Дата поступления')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.schoolclass', verbose_name='Класс')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'История обучения',
                'verbose_name_plural': 'Истории обучения',
                'ordering': ['-date_from'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='classes_history',
            field=models.ManyToManyField(through='school.StudentClassHistory', to='school.schoolclass', verbose_name='История обучения в классах'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='school.employee')),
                ('classes_teaches', models.ManyToManyField(blank=True, related_name='teachers', to='school.schoolclass', verbose_name='Классы (преподавание)')),
                ('subjects', models.ManyToManyField(blank=True, to='school.subject', verbose_name='Преподаваемые предметы')),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
            },
            bases=('school.employee',),
        ),
    ]
