# Generated by Django 6.0.5 on 2026-05-12 14:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='Россия', max_length=100, verbose_name='Страна')),
                ('region', models.CharField(max_length=100, verbose_name='Регион (Край/Область)')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='Район')),
                ('city', models.CharField(max_length=100, verbose_name='Город/Село')),
                ('street', models.CharField(max_length=150, verbose_name='Улица')),
                ('building_number', models.CharField(max_length=10, verbose_name='Номер дома/строения')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Почтовый индекс')),
                ('description', models.TextField(blank=True, verbose_name='Примечание к адресу')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название должности')),
                ('description', models.TextField(blank=True, verbose_name='Описание должности')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('description', models.TextField(blank=True, verbose_name='О себе или примечания')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photos/', verbose_name='Фотография ученика')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название предмета')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название школы')),
                ('description', models.TextField(blank=True, verbose_name='Описание школы')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='school_photos/', verbose_name='Логотип или фото школы')),
                ('addresses', models.ManyToManyField(blank=True, to='school.address', verbose_name='Адреса школы')),
            ],
            options={
                'verbose_name': 'Школа',
                'verbose_name_plural': 'Школы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('hire_year', models.IntegerField(verbose_name='Год приема на работу')),
                ('description', models.TextField(blank=True, verbose_name='О сотруднике')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee_photos/', verbose_name='Фотография сотрудника')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.position', verbose_name='Занимаемая должность')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school', verbose_name='Место работы')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900)], verbose_name='Год начала обучения')),
                ('end_year', models.IntegerField(editable=False, verbose_name='Год окончания обучения')),
                ('grade_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Номер класса')),
                ('letter', models.CharField(blank=True, max_length=1, null=True, verbose_name='Буква класса')),
                ('description', models.TextField(blank=True, verbose_name='Описание класса')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='class_photos/', verbose_name='Фото класса')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school', verbose_name='Учебное заведение')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
                'ordering': ['start_year', 'grade_number', 'letter'],
            },
        ),
        migrations.CreateModel(
            name='StudentClassHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='Дата поступления')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.schoolclass', verbose_name='Класс')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'История обучения',
                'verbose_name_plural': 'Истории обучения',
                'ordering': ['-date_from'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='classes_history',
            field=models.ManyToManyField(through='school.StudentClassHistory', to='school.schoolclass', verbose_name='История обучения в классах'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='school.employee')),
                ('classes_teaches', models.ManyToManyField(blank=True, related_name='teachers', to='school.schoolclass', verbose_name='Классы (преподавание)')),
                ('subjects', models.ManyToManyField(blank=True, to='school.subject', verbose_name='Преподаваемые предметы')),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
            },
            bases=('school.employee',),
        ),
    ]
